### ISSUE TITLE
Allow rich rules

### ISSUE THREAD

**Issue by timwsuqld** [tinuva/firewalld-formula#7]
As far as I can tell, I need to use rich rules to achieve what I want to achieve.
We want to open access to a port, but only for specific hosts.
e.g.
All hosts can SSH
Only 192.168.0.34 can access port 80

or

All hosts can SSH
Only 192.168.0.34, 10.1.4.3 and 192.168.2.0/24 can access port 80

There is the destination option in a service, however this is for the other way, for outgoing traffic (as best as I can determine from reading the docs and experimenting). I also can't see any way to be in more than one zone, so being able to use rich_rules on a zone doesn't help.

**Comment by tinuva** [comment]
You do want to make use of Zones, but instead of having a SSH zone, you have a "source host" zone. Or to put it differently, instead of having source hosts in multiple zones, you want services in multiple zones.

So try this:
All hosts zone:
Allow SSH

Zone for 192.168.0.34 call it ZoneTwo:
Allow SSH
Allow HTTP

Zone for 10.1.4.3 and 192.168.2.0/24 call it ZoneThree:
Allow SSH
Allow HTTP

The destination option is allowed by FirewallD, not per say a limit imposed  by the firewalld-formula.

I hope that helps.

**Comment by tinuva** [comment]
Let me add a pillar example for you:

```
  zones:
    {# Public Zone - no inbound access required #}
    public:
      short: Public
      description: "For use in public areas."
      services:
        - ssh
    {# Zone for a single host #}
    zonetwo:
      short: zonetwo
      description: "Allow port 80 additional to SSH for this host"
      sources:
        - 192.168.0.34/32
      services:
        - ssh
        - http
```
